### ISSUE TITLE
Warning when using the quick_log 5.2.0

### ISSUE THREAD

**Issue by dominikheeb** [MohiuddinM/log#1]
When I use your library i get a warning in the console about a not needed ! operator in your code.

```../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/quick_log-5.2.0/lib/src/log_writer.dart:121:22: 
Warning: Operand of null-aware operation '!' has type 'LogMessage' which excludes null.
 - 'LogMessage' is from 'package:quick_log/src/log_message.dart' ('../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/quick_log-5.2.0/lib/src/log_message.dart').
    return _messages.value!;
```

could you please fix this, so that there is not a warning in the code present when starting.

**Comment by dominikheeb** [comment]
https://github.com/MohiuddinM/log/pull/2

Here is a pull request to remove the issue with the warning

**Comment by MohiuddinM** [comment]
The PR you opened contains an error. I have pushed a commit, please test if it solves your problem.

**Comment by dominikheeb** [comment]
Thx for the commit. It seems to solve our issue. Can you publish the fix on pub.dev?

**Comment by dominikheeb** [comment]
i will close and remove my pr since your solution works better :)

**Comment by dominikheeb** [comment]
thanks for the new version. it fixed our issue.
